### ISSUE TITLE
Can't call .stream on Document

### ISSUE THREAD

**Issue by nocoli** [ruby-docx/docx#82]
I need to get the current state as an IO - ready to be uploaded. I can see the stream method when I look at the Document class but get the following error when I try and call it:
```
NoMethodError:
       undefined method `stream' for #<Docx::Document:0x000055fa7bb472a8>
```

Example of what I am trying to do:
```
doc = Docx::Document.open(downloaded_file)
# make changes to doc.zip
stream = doc.stream
```

**Comment by satoryu** [comment]
@nocoli thank you for opening this issue.  
Which version of `docx`  are you using?

**Comment by nocoli** [comment]
@satoryu Using docx-0.4.0.

After running `gem install docx` I can navigate to the gem on my local machine and can see inside `docx-0.4.0/lib/docx.document.rb` that the stream method is not present for some reason

**Comment by satoryu** [comment]
Ah... the PR #66 for `Docx::Document#stream` was merged after releasing v0.4.0. 
The feature is going to be shipped as next version.

**Comment by satoryu** [comment]
if you want to use it, you install the edge version by adding/updating `Gemfile` for your app:

```ruby
gem 'docx', github: 'ruby-docx/docx'
```

**Comment by satoryu** [comment]
I started preparing for next release v0.5 #86 . This release includes `Docx::Document#stream`.

**Comment by satoryu** [comment]
@nocoli released v0.5.0 🎉 

I confirmed `stream` works with v0.5:

```irb
irb(main):001:0> require 'docx'
=> true
irb(main):002:0> Docx::VERSION
=> "0.5.0"
irb(main):003:0> doc = Docx::Document.open('/Users/satoryu/Downloads/Document.docx')
WARNING: Nokogiri was built against LibXML version 2.9.10, but has dynamically loaded 2.9.4
irb(main):004:0> doc.stream
=> #<StringIO:0x00007fca1d8ffce8>
```
